### ISSUE TITLE
Future tasks

### ISSUE THREAD

**Issue by paulbellmann** [paulbellmann/Berichtsheft#1]
## ToDo:
- [x] Python or ASP code that generates input files (replace)
- [x] Separate `.aux` and co in different folder
- [x] Vorschau für `README.md`
- [x] Rechtschreibung (import German?)

**Comment by paulbellmann** [comment]
good ideas
